# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MySub'
    subscriptionId: '4842877b-e30c-47d2-9ed2-7e78de64802d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'testwindows'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/arzuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/azuredeploy.parameters'
    deploymentMode: 'Incremental'
